## Porta ##
server:
  port: 8761

## Config para bloquear o servidor de se auto-registrar  
## fetch-registry controla o acesso ao servidor eureka ##
## register-with-eureka controla o registro ao servidor eureka ##
## Porta padrao 8761 ##
eureka:
  client:
    fetch-registry: false 
    register-with-eureka: false 
